// Generated by FlutterFire CLI. Replace placeholder values by running:
//   flutterfire configure --project=<your-firebase-project-id>
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WEB_API_KEY',
    appId: '1:REPLACE:web:REPLACE',
    messagingSenderId: 'REPLACE_SENDER_ID',
    projectId: 'crew-link',
    authDomain: 'crew-link.firebaseapp.com',
    databaseURL: 'https://crew-link-default-rtdb.firebaseio.com',
    storageBucket: 'crew-link.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_ANDROID_API_KEY',
    appId: '1:REPLACE:android:REPLACE',
    messagingSenderId: 'REPLACE_SENDER_ID',
    projectId: 'crew-link',
    databaseURL: 'https://crew-link-default-rtdb.firebaseio.com',
    storageBucket: 'crew-link.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: '1:REPLACE:ios:REPLACE',
    messagingSenderId: 'REPLACE_SENDER_ID',
    projectId: 'crew-link',
    databaseURL: 'https://crew-link-default-rtdb.firebaseio.com',
    storageBucket: 'crew-link.firebasestorage.app',
    iosClientId: 'REPLACE_IOS_CLIENT_ID',
    iosBundleId: 'com.crewlink.crewLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_MACOS_API_KEY',
    appId: '1:REPLACE:macos:REPLACE',
    messagingSenderId: 'REPLACE_SENDER_ID',
    projectId: 'crew-link',
    databaseURL: 'https://crew-link-default-rtdb.firebaseio.com',
    storageBucket: 'crew-link.firebasestorage.app',
    iosClientId: 'REPLACE_MACOS_CLIENT_ID',
    iosBundleId: 'com.crewlink.crewLink',
  );
}
